[package]
name = "anvil-server"
description = "Customizable RPC server"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# axum related
axum = { workspace = true, features = ["ws"] }
tower-http = { workspace = true, features = ["trace", "cors"] }

# tracing
tracing.workspace = true

# async
parking_lot.workspace = true
futures.workspace = true
tokio = { version = "1", features = ["full"] }

# ipc
interprocess = { workspace = true, optional = true }
bytes = { workspace = true, optional = true }
tokio-util = { workspace = true, features = ["codec"], optional = true }

# misc
serde_json.workspace = true
serde.workspace = true
async-trait.workspace = true
thiserror.workspace = true

clap = { version = "4", features = ["derive", "env"], optional = true }
pin-project = "1"

# anvil crates
anvil-rpc = { path = "../rpc" }

[dev-dependencies]
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }

[features]
default = ["ipc"]
ipc = ["dep:interprocess", "dep:bytes", "dep:tokio-util"]
clap = ["dep:clap"]
